CREATE TABLE T20.AU_FAVORITEN
(
  AU_AID    NUMBER,
  AU_USER   VARCHAR2(8)
);
CREATE OR REPLACE PUBLIC SYNONYM AU_FAVORITEN FOR T20.AU_FAVORITEN;
GRANT SELECT ON T20.AU_FAVORITEN TO GDV;
GRANT SELECT ON T20.AU_FAVORITEN TO RL_BIPRO;
GRANT SELECT ON T20.AU_FAVORITEN TO RL_LESEN;
GRANT DELETE, INSERT, SELECT, UPDATE ON T20.AU_FAVORITEN TO RL_SCHREIBEN;
GRANT SELECT ON T20.AU_FAVORITEN TO TESTER;

CREATE TABLE T20.AU_AUSWERTUNGEN
(
  AU_AID           NUMBER,
  AU_ART           VARCHAR2(40),
  AU_VERTRIEBSKZ   VARCHAR2(8),
  AU_BEREICH       VARCHAR2(50),
  AU_DATUM         DATE,
  AU_TITEL         VARCHAR2(60),
  AU_BESCHREIBUNG  VARCHAR2(3000),
  AU_SQL           CLOB
);
ALTER TABLE T20.AU_AUSWERTUNGEN ADD (
  CONSTRAINT AU_AUSWERTUNGEN_PK
  PRIMARY KEY
  (AU_AID)
  ENABLE VALIDATE);
CREATE OR REPLACE PUBLIC SYNONYM AU_AUSWERTUNGEN FOR T20.AU_AUSWERTUNGEN;
GRANT SELECT ON T20.AU_AUSWERTUNGEN TO GDV;
GRANT SELECT ON T20.AU_AUSWERTUNGEN TO RL_BIPRO;
GRANT SELECT ON T20.AU_AUSWERTUNGEN TO RL_LESEN;
GRANT DELETE, INSERT, SELECT, UPDATE ON T20.AU_AUSWERTUNGEN TO RL_SCHREIBEN;
GRANT SELECT ON T20.AU_AUSWERTUNGEN TO TESTER;

CREATE TABLE T20.AU_INSTANZEN
(
  AU_IID    NUMBER,
  AU_AID    NUMBER,
  AU_DATUM  DATE,
  AU_USER   VARCHAR2(8),
  AU_PFAD   VARCHAR2(1000),
  AU_DAUER  NUMBER
);
ALTER TABLE T20.AU_INSTANZEN ADD (
  CONSTRAINT AU_INSTANZEN_PK
  PRIMARY KEY
  (AU_IID)
  ENABLE VALIDATE);
CREATE OR REPLACE PUBLIC SYNONYM AU_INSTANZEN FOR T20.AU_INSTANZEN;
GRANT SELECT ON T20.AU_INSTANZEN TO GDV;
GRANT SELECT ON T20.AU_INSTANZEN TO RL_BIPRO;
GRANT SELECT ON T20.AU_INSTANZEN TO RL_LESEN;
GRANT DELETE, INSERT, SELECT, UPDATE ON T20.AU_INSTANZEN TO RL_SCHREIBEN;
GRANT SELECT ON T20.AU_INSTANZEN TO TESTER;

CREATE TABLE T20.AU_AUSWERTUNGSPARAMETER
(
  AU_AID  NUMBER,
  AU_PID  NUMBER
);
CREATE OR REPLACE PUBLIC SYNONYM AU_AUSWERTUNGSPARAMETER FOR T20.AU_AUSWERTUNGSPARAMETER;
GRANT SELECT ON T20.AU_AUSWERTUNGSPARAMETER TO GDV;
GRANT SELECT ON T20.AU_AUSWERTUNGSPARAMETER TO RL_BIPRO;
GRANT SELECT ON T20.AU_AUSWERTUNGSPARAMETER TO RL_LESEN;
GRANT DELETE, INSERT, SELECT, UPDATE ON T20.AU_AUSWERTUNGSPARAMETER TO RL_SCHREIBEN;
GRANT SELECT ON T20.AU_AUSWERTUNGSPARAMETER TO TESTER;

CREATE TABLE T20.AU_PARAMETER
(
  AU_PID          NUMBER,
  AU_PARAMNAME    VARCHAR2(100),
  AU_TYP          VARCHAR2(20),
  AU_BEZEICHNUNG  VARCHAR2(60),
  AU_ERKLAERUNG   VARCHAR2(50),
  AU_DEFAULT      VARCHAR2(100),
  AU_STMT         VARCHAR(1000),
  AU_REGEX        VARCHAR2(20)
);
ALTER TABLE T20.AU_PARAMETER ADD (
  CONSTRAINT AU_PARAMETER_PK
  PRIMARY KEY
  (AU_PID)
  ENABLE VALIDATE);
CREATE OR REPLACE PUBLIC SYNONYM AU_PARAMETER FOR T20.AU_PARAMETER;
GRANT SELECT ON T20.AU_PARAMETER TO GDV;
GRANT SELECT ON T20.AU_PARAMETER TO RL_BIPRO;
GRANT SELECT ON T20.AU_PARAMETER TO RL_LESEN;
GRANT DELETE, INSERT, SELECT, UPDATE ON T20.AU_PARAMETER TO RL_SCHREIBEN;
GRANT SELECT ON T20.AU_PARAMETER TO TESTER;



--Befüllung zum Test:
INSERT INTO AU_AUSWERTUNGEN VALUES(1, 'Atomare Liste', 'TELIS', 'Mandanten', SYSDATE, 'Testauswertung', 'Eine Auswertung zum testen', 'SELECT * FROM Antraege WHERE AN_VERTRIEBSKZ = :vertriebskz');
INSERT INTO AU_PARAMETER VALUES(1, ':vertriebskz', 'auswahl', 'VertriebsKZ', 'Vertriebskürzel', 'T', 'SELECT vt_vertriebskz, vt_vertriebsbez FROM vertriebe', NULL);
INSERT INTO AU_AUSWERTUNGSPARAMETER VALUES(1, 1);
INSERT INTO AU_FAVORITEN VALUES(1, 'MLINDE');
INSERT INTO AU_FAVORITEN VALUES(1, 'PRIEGER');
COMMIT;